const authConstants = {
  SIGN_UP_REQUESTED: "SIGN_UP_REQUESTED",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",

  LOGIN_REQUESTED: "LOGIN_REQUESTED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT: "LOGOUT",

  RESET_PASSWORD_REQUESTED: "RESET_PASSWORD_REQUESTED",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",

  SET_PASSWORD_REQUESTED: "SET_PASSWORD_REQUESTED",
  SET_PASSWORD_SUCCESS: "SET_PASSWORD_SUCCESS",
  SET_PASSWORD_FAILURE: "SET_PASSWORD_FAILURE",

  CHANGE_PASSWORD_REQUESTED: "CHANGE_PASSWORD_REQUESTED",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",

  COUNTRY_FETCH_SUCCESS: "COUNTRY_FETCH_SUCCESS",
  COUNTRY_FETCH_FAILURE: "COUNTRY_FETCH_FAILURE",

  CITY_FETCH_SUCCESS: "CITY_FETCH_SUCCESS",
  CITY_FETCH_FAILURE: "CITY_FETCH_FAILURE",
};

export default authConstants;
