const labConstants = {
    USER_LIST_SUCCESS : "USER_LIST_SUCCESS",
    USER_LIST_FAILURE : "USER_LIST_FAILURE",

    KIT_LIST_SUCCESS : "KIT_LIST_SUCCESS",
    KIT_LIST_FAILURE : "KIT_LIST_FAILURE",

    MACHINE_LIST_SUCCESS : "MACHINE_LIST_SUCCESS",
    MACHINE_LIST_FAILURE : "MACHINE_LIST_FAILURE"
}

export default labConstants;